name: pikaday_datepicker_angular
description: Provides a datepicker for Angular4 component which wrapps the lightweight pikaday js-library.
version: 3.0.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular
environment:
  sdk: '>=1.24.0 <1.25.0'
dependencies:
  angular: '>=4.0.0 <5.0.0'
  js: ^0.6.1
  pikaday:
    git:
      url: https://github.com/simon-void/pikaday-dart.git
      ref: master
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
### (default) configuration if this package should be used as a library (import) or if the app should be execute as Dart in Dartium
- angular
### configuration if example web folder should be compiled to js
#- angular:
#    entry_points: web/main.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
